# Generated by Django 5.2.1 on 2025-05-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_create_initial_spaces'),
        ('parking', '0002_reservation_user'),
    ]

    operations = [
    ]
