# Generated by Django 5.2.1 on 2025-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_merge_20250518_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_disabled_spot',
            field=models.BooleanField(default=False, verbose_name='Espacio para discapacitados'),
        ),
    ]
