# Generated by Django 5.2.1 on 2025-05-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_add_parking_rates'),
        ('parking', '0005_designate_disabled_spots'),
    ]

    operations = [
    ]
