# Generated by Django 5.2.1 on 2025-06-06 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_merge_20250529_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspace'),
        ),
    ]
