# Generated by Django 5.0.2 on 2025-04-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='car_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca del Vehículo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo del Vehículo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/', verbose_name='Foto del Vehículo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Teléfono'),
        ),
    ]
