# Generated by Django 5.2.1 on 2025-05-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_roles'),
        ('users', '0003_dynamicpricing_membershiplevel_role_membership_and_more'),
    ]

    operations = [
    ]
