# Generated by Django 5.0.2 on 2025-06-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_twofactorauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#007bff', help_text='Color principal en formato hexadecimal', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Color secundario en formato hexadecimal', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Color de fondo en formato hexadecimal', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Color del texto en formato hexadecimal', max_length=7)),
                ('font_family', models.CharField(default='Arial', help_text='Familia de fuente principal', max_length=100)),
                ('heading_font_size', models.CharField(default='24px', help_text='Tamaño de fuente para encabezados', max_length=10)),
                ('body_font_size', models.CharField(default='16px', help_text='Tamaño de fuente para el texto normal', max_length=10)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='theme/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon del sitio', null=True, upload_to='theme/favicons/')),
                ('company_name', models.CharField(default='Mi Empresa', help_text='Nombre de la empresa', max_length=100)),
                ('welcome_message', models.TextField(default='Bienvenido a nuestro sistema', help_text='Mensaje de bienvenida')),
                ('button_radius', models.CharField(default='4px', help_text='Radio de borde para botones', max_length=10)),
                ('button_padding', models.CharField(default='10px 20px', help_text='Padding para botones', max_length=10)),
                ('card_radius', models.CharField(default='8px', help_text='Radio de borde para tarjetas', max_length=10)),
                ('card_shadow', models.CharField(default='0 2px 4px rgba(0,0,0,0.1)', help_text='Sombra para tarjetas', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta configuración está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tema',
                'verbose_name_plural': 'Configuraciones de Tema',
            },
        ),
    ]
