# Generated by Django 5.0.2 on 2025-06-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPanelTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del tema')),
                ('is_active', models.BooleanField(default=False, verbose_name='Tema activo')),
                ('primary_color', models.CharField(default='#3498db', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#2ecc71', max_length=7, verbose_name='Color secundario')),
                ('accent_color', models.CharField(default='#f1c40f', max_length=7, verbose_name='Color de acento')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Color de fondo')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='Color del texto')),
                ('heading_font', models.CharField(default="'Roboto', sans-serif", max_length=100, verbose_name='Fuente de títulos')),
                ('body_font', models.CharField(default="'Open Sans', sans-serif", max_length=100, verbose_name='Fuente del texto')),
                ('heading_size', models.CharField(default='2rem', max_length=20, verbose_name='Tamaño de títulos')),
                ('body_size', models.CharField(default='1rem', max_length=20, verbose_name='Tamaño del texto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_panel/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='client_panel/favicons/', verbose_name='Favicon')),
                ('card_radius', models.CharField(default='12px', max_length=20, verbose_name='Radio de bordes de tarjetas')),
                ('button_radius', models.CharField(default='8px', max_length=20, verbose_name='Radio de bordes de botones')),
                ('shadow_effect', models.CharField(default='0 4px 6px rgba(0,0,0,0.1)', max_length=100, verbose_name='Efecto de sombra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema del panel de cliente',
                'verbose_name_plural': 'Temas del panel de cliente',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
    ]
