# Generated by Django 5.0.2 on 2025-06-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clientpaneltheme_delete_themesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPanelTheme',
        ),
    ]
