# Generated by Django 5.2.1 on 2025-05-19 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carwashservice',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='carwashservice',
            name='name',
        ),
        migrations.AddField(
            model_name='carwashservice',
            name='service_type',
            field=models.CharField(choices=[('BASIC_WASH', 'Lavado Básico'), ('WAX', 'Encerado'), ('INTERIOR', 'Limpieza Interior'), ('FULL_SERVICE', 'Servicio Completo')], default='BASIC_WASH', max_length=50),
        ),
        migrations.AddField(
            model_name='carwashservice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='carwashservice',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='carwashservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
