version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: park_app
    container_name: park_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - DATABASE_URL=postgresql://parking_user:zIa9A8kicLBDh8hC4k6xq4DZXH9oQGfw@dpg-d13s1c8gjchc73fgk4t0-a.oregon-postgres.render.com/parking_db_3of6
      - DJANGO_SETTINGS_MODULE=parking_system.settings
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: park_db
    restart: always
    environment:
      - POSTGRES_DB=parking_db_3of6
      - POSTGRES_USER=parking_user
      - POSTGRES_PASSWORD=zIa9A8kicLBDh8hC4k6xq4DZXH9oQGfw
      - POSTGRES_HOST=dpg-d13s1c8gjchc73fgk4t0-a.oregon-postgres.render.com
    ports:
      - "5432:5432"

networks:
  park_network:
    driver: bridge

volumes:
  postgres_data: 
  redis_data: 