version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: park_app
    container_name: park_app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - park_network

  nginx:
    image: nginx:1.21-alpine
    container_name: park_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - park_network

  db:
    image: postgres:13
    container_name: park_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - park_network

  redis:
    image: redis:6-alpine
    container_name: park_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - park_network

networks:
  park_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 