services:
  - type: web
    name: parking-system
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: parking.settings
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: parking-db
          property: connectionString
    autoDeploy: true

databases:
  - name: parking-db
    databaseName: parking
    plan: free 