# Generated by Django 5.0.2 on 2025-06-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitestyle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteStyle',
        ),
    ]
