# Generated by Django 5.2.1 on 2025-05-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_alter_invoice_options_remove_invoice_client_and_more'),
    ]

    operations = [
    ]
